
name: CI

on:
  push:
    branches: [ "test" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anyakichi/aosp-builder:14.04
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}


    steps:
      - uses: actions/checkout@v3
        with: 
          repository: 'MiCode/Xiaomi_Kernel_OpenSource'
          ref: latte-l-oss
          fetch-depth: '1'

      - name: Clone  tools
        uses: actions/checkout@v3
        with: 
          repository: 'AOSHP/prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9'
          path: x86_64-linux-android-4.9

      - name: (Debug)Output build env
        run: |
          ls
          echo
          ls x86_64-linux-android-4.9
          echo
          ls x86_64-linux-android-4.9/bin

      - name: Build
        run: |
          export ARCH=x86_64
          export SUBARCH=x86_64
          export CROSS_COMPILE=x86_64-linux-android-4.9/bin/x86_64-linux-android-

          mkdir out

          make O=out defconfig
          make O=out -j8
