
name: CI

on:
  push:
    branches: [ "test" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anyakichi/aosp-builder:14.04
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}


    steps:
      - uses: actions/checkout@v3
        with: 
          repository: 'MiCode/Xiaomi_Kernel_OpenSource'
          ref: latte-l-oss
          fetch-depth: '1'

      - name: Clone  tools
        uses: actions/checkout@v3
        with: 
          repository: 'Zenfone2-Dev/x86_64-linux-android-4.9'
          path: x86_64-linux-android-4.9

      - name: (Debug)Output build env
        run: |
          ls
          echo
          ls x86_64-linux-android-4.9
          echo
          ls x86_64-linux-android-4.9/bin
          echo
          ls /lib64/ld-linux-x86-64.so.2
          ls /lib/x86_64-linux-gnu/libm.so.6
          ls /lib/x86_64-linux-gnu/libc.so.6
          echo
          ls /etc/ld.so.conf.d/*


      - name: Fix
        run: |
          echo nothing to do.

      - name: Build
        run: |
          export ARCH=x86_64
          export SUBARCH=x86_64
          export PATH=$PATH:./x86_64-linux-android-4.9/bin/
          export CROSS_COMPILE=x86_64-linux-android-

          mkdir out

          make O=out defconfig
          make O=out -j8
