
name: CI

on:
  push:
    branches: [ "test" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: 'MiCode/Xiaomi_Kernel_OpenSource'
          ref: latte-l-oss
          fetch-depth: '1'

      - name: Clone  tools
        run: |
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts
          ls prebuilts

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
