
name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    #    container:
    #      image: ghcr.io/anyakichi/aosp-builder:14.04
    #      credentials:
    #        username: ${{ github.actor }}
    #        password: ${{ secrets.github_token }}

        #    container:
        #      image: ghcr.io/tunathu/aosp-monthly:latest
        #      credentials:
        #        username: ${{ github.actor }}
        #        password: ${{ secrets.github_token }}



    steps: 
      - mame:
        run: |
          echo Nothing to do.

      - name: Output host env
        run: |
          gcc -v
          python3 -V
          ls

      - name: Download repo tool
        run: |
          mkdir ~/bin
          PATH=~/bin:$PATH
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: init repo
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b android-5.1.1_r38

      - name: Download android source trees
        run: |
          repo sync

      - uses: actions/checkout@v3
        with: 
          repository: 'MiCode/Xiaomi_Kernel_OpenSource'
          ref: latte-l-oss
          path: la_kernel
    
    #      - uses: actions/checkout@v3
    #        with: 
    #          repository: 'torvalds/linux'
    #          ref: v3.10






      - name: Fix Makefile
        run: |
          sed -i '381 a -fno-pie\\' Makefile

      - name: Generate config file
        run: |
          make help
          make defconfig ARCH=x86_64
          make kvmconfig ARCH=x86_64

      - name: Build the kernel
        run: |
          make modules
