# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: hub.docker.com/anyakichi/aosp-builder

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
              with: 
                repository: 'MiCode/Xiaomi_Kernel_OpenSource'
                ref: latte-l-oss

      #      - uses: actions/checkout@v3
      #        with: 
      #          repository: 'torvalds/linux'
      #          ref: v3.10

      - name: Output host env
        run: |
          gcc -v
          ls
      - name: Fix Makefile
        run: |
          sed -i '381 a -fno-pie\\' Makefile

      # Runs a single command using the runners shell
      - name: Generate config file
        run: |
          make help
          make defconfig ARCH=x86_64
          make kvmconfig ARCH=x86_64

      # Runs a set of commands using the runners shell
      - name: Build the kernel
        run: |
          make modules
