
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: 'MiCode/Xiaomi_Kernel_OpenSource'
          ref: latte-l-oss
          fetch-depth: '1'

      - uses: actions/checkout@v3
        with: 
          repository: 'android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9'
          fetch-depth: '1'

      - name: Run a one-line script
        run: ls kernel

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
